version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: maya
      POSTGRES_PASSWORD: mayapass
      POSTGRES_DB: mayadb
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
